### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by Priyankadas16** [unchartedsoftware/influent#3]
Hi , i am getting following build failure message 

Failed to execute goal on project influent-server: Could not resolve dependencies for project oculus.influent:influent-server:jar:1.3.6: The following artifacts could not be resolved: oculus.aperture:aperture-spi:jar:1.0.9, oculus.aperture:aperture-server-core:jar:1.0.9, oculus.aperture.service:aperture-icons:jar:1.0.9, oculus.aperture.service:aperture-parchment:jar:1.0.9, oculus.aperture.service:aperture-cms:jar:1.0.9, oculus.aperture.service:aperture-capture-phantom:jar:1.0.9: Failure to find oculus.aperture:aperture-spi:jar:1.0.9 in http://mavenrepo.google-api-java-client.googlecode.com/hg was cached in the local repository, resolution will not be reattempted until the update interval of google-api-services has elapsed or updates are forced -> [Help 1]

**Comment by jamespr** [comment]
Hello, 

From the build failure message you are getting, it would appear that Aperture dependencies are missing. 

Before building Influent, you will need to build the following dependencies:

* [ApertureJS](https://github.com/unchartedsoftware/aperturejs)
* [Oculus Ensemble Clustering](https://github.com/oculusinfo/ensemble-clustering)

Then run:
```
mvn clean install
```

If you've done that and are still having build errors, then please let me know.

Thanks,

James Robinson
Senior Visualization Developer | Uncharted™
formerly Oculus Info Inc.

**Comment by Priyankadas16** [comment]
Hi James,

Thanks for your reply. I am following the steps and getting this error in
mvn clean install.

Regards
Priyanka

**Comment by jamespr** [comment]
Hi Priyanka,

My apologies. It would appear that the link to ApertureJS is to version 1.1.0, while Influent is looking for 1.0.9.

ApertureJS [master branch](https://github.com/unchartedsoftware/aperturejs/tree/master) is 1.0.9.

Give that a try and let me know. I'll also change the readme accordingly.

Thanks,
James

**Comment by felipevb** [comment]
I just so happen to hit this problem a few hours ago and saw the new commit on the README. One thing to point out, when i still do a "git clone https://github.com/unchartedsoftware/aperturejs.git", it pulls the develop branch. To work around is to do a "git checkout master"

**Comment by Priyankadas16** [comment]
Hi James,

Thank you, now its working fine.

Regards
Priyanka

**Comment by Priyankadas16** [comment]
Hi,

I am trying to run influent on my system, its build properly. But when i am
trying to run kiva with mvn package jetty:run  its giving exception as
database not accessible.
How i can build or configure local data base for kiva.

Regards
Priyanka

**Comment by jamespr** [comment]
Hi Priyanka,

By default, the Kiva example app is pointing to the full Kiva dataset at orange.oculusinfo.com.

If you're having trouble reaching this server or are trying to use Influent offline, then we have a smaller subset of the Kiva data available as part of a demo distribution here: http://community.influent.org/community/download/

This distribution points to a local database. Unzip and double-click the appropriate start script for your OS to launch it, and open http://localhost:8080/kiva/ in your browser.

If you want to point your existing Influent deployment to this database, you'll need to modify your app.properties configuration file accordingly. In \kiva\src\main\resources\app.properties, change the "Midtier Server Properties" to:

`influent.midtier.database.url = jdbc:hsqldb:file:../data/db`
`influent.midtier.database.driver = org.hsqldb.jdbcDriver`
`influent.midtier.user.name = SA`
`influent.midtier.user.password = `
`influent.midtier.solr.url = http://localhost:8080/solr/demoKivaSolr`

And ensure that Solr is running with the demoKivaSolr core.

James Robinson
Senior Visualization Developer | Uncharted™
formerly Oculus Info Inc.

**Comment by Priyankadas16** [comment]
Hi James,

Thanks for reply it was really helpful. Now i am facing another issue, when
i access http://localhost:8080/kiva

it throws a NullPointerException with given message in log file.

org.apache.catalina.core.StandardContext.listenerStart Exception sending
context initialized event to listener instance of class
oculus.aperture.ApertureServerConfig
 com.google.inject.CreationException: Guice creation errors:

1) No implementation for java.lang.String annotated with
@com.google.inject.name.Named(value=influent.midtier.solr.descriptor) was
bound.
  at
influent.kiva.server.spi.KivaFLAnonEntitySearchModule.connect(KivaFLAnonEntitySearchModule.java:66)

1 error
at
com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
at
com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
at
com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
at com.google.inject.Guice.createInjector(Guice.java:95)
at com.google.inject.Guice.createInjector(Guice.java:72)
at
oculus.aperture.ApertureServerConfig.getInjector(ApertureServerConfig.java:165)
at
com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
at
oculus.aperture.ApertureServerConfig.contextInitialized(ApertureServerConfig.java:137)
at
org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738)
at
org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5158)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at
org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:702)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:697)
at
org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:579)
at
org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1744)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

 Please suggest

Regards
Priyanka

**Comment by jamespr** [comment]
This error means that you don't have a definition for influent.midtier.solr.descriptor in your app.properties configuration.

this value should point to the address of your solr server, as above: 

`influent.midtier.solr.url = http://localhost:8080/solr/demoKivaSolr`
